# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('category', models.CharField(choices=[('T', 'تعزیه'), ('O', 'عمومی')], max_length=2, verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
