# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 12:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تلفن')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس')),
                ('father_name', models.CharField(max_length=500, verbose_name='نام پدر')),
                ('year_of_birth', models.PositiveIntegerField(verbose_name='سال تولد')),
                ('classes', models.ManyToManyField(related_name='students', to='education.Class', verbose_name='کلاس\u200cها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'هنرآموز',
                'verbose_name_plural': 'هنرآموزان',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تلفن')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس')),
                ('classes', models.ManyToManyField(related_name='teachers', to='education.Class', verbose_name='کلاس\u200cها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'معلم',
                'verbose_name_plural': 'معلمان',
            },
        ),
    ]
