# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='test', max_length=200, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='test', max_length=200, verbose_name='نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default='test', max_length=200, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default='test', max_length=200, verbose_name='نام خانوادگی'),
            preserve_default=False,
        ),
    ]
