# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import education.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20180316_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='national_code',
            field=models.CharField(max_length=10, validators=[education.models.national_code_validator], verbose_name='کد ملی'),
        ),
    ]
