# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import education.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20180317_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('confirmed', models.BooleanField(default=False, verbose_name='تاییدشده')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='education.Class', verbose_name='کلاس دریافت کننده')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیامها',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(validators=[education.models.address_validator], verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.TextField(validators=[education.models.address_validator], verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='education.Teacher', verbose_name='فرستنده'),
        ),
    ]
