# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='videos/', verbose_name='عکس')),
                ('title', models.CharField(max_length=1000, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('category', models.CharField(choices=[('G', 'قودجان'), ('H', 'همایش'), ('T', 'تعزیه'), ('M', 'مراسمات و برنامه\u200cها')], max_length=2, verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'کلیپ',
                'verbose_name_plural': 'کلیپ\u200cها',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس')),
                ('category', models.CharField(choices=[('G', 'قودجان'), ('M', 'مجمع تعزیه آل طه'), ('O', 'عمومی')], max_length=2, verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/', verbose_name='ویدیو')),
                ('title', models.CharField(max_length=1000, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('category', models.CharField(choices=[('N', 'خبر'), ('R', 'روضه\u200cخوانی'), ('M', 'مرثیه')], max_length=2, verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیوها',
            },
        ),
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/', verbose_name='ویدیو')),
                ('title', models.CharField(max_length=1000, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('category', models.CharField(choices=[('O', 'عمومی'), ('T', 'تعزیه')], max_length=2, verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'کلیپ',
                'verbose_name_plural': 'کلیپ\u200cها',
            },
        ),
    ]
