# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20180312_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsgroup',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='news_groups', to='education.Student', verbose_name='هنرجویان'),
        ),
        migrations.AlterField(
            model_name='newsgroup',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='news_groups', to='education.Teacher', verbose_name='معلمان'),
        ),
    ]
