# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 18:24
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20180317_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس'),
        ),
    ]
